apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    app: "{{ .Chart.Name }}"
    {{- if .Values.global.clientConfig.bcGov.enabled }}
    DataClass: {{ .Values.global.clientConfig.bcGov.dataClass | quote }}
    {{- end }}
spec:
  ports:
  - name: "{{ .Chart.Name }}"
    port: {{ .Values.ingress.port }}
    protocol: TCP
    targetPort: {{ .Values.ingress.port }}
  selector:
    app: "{{ .Chart.Name }}"
