---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: "{{ .Chart.Name }}-scheduler"
  name: "{{ .Chart.Name }}-scheduler"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}-scheduler"
  strategy: {}
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}-scheduler"
    spec:
      restartPolicy: Always
      securityContext:
        fsGroup: 2000 # Setting the file system group
      containers:
        - name: "{{ .Chart.Name }}-scheduler"
          image: "{{ .Values.redash.image.registry }}/{{ .Values.redash.image.repository }}:{{ .Values.redash.image.tag }}"
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          args:
            - scheduler
          envFrom:
            - configMapRef:
                name: "{{ .Chart.Name }}" # default redash environment variables
            - secretRef:
                name: "{{ .Chart.Name }}" # default redash environment variables
          resources:
            limits:
              cpu: "{{ .Values.resources.limits.cpu }}"
              memory: "{{ .Values.resources.limits.memory }}"
            requests:
              cpu: "{{ .Values.resources.requests.cpu }}"
              memory: "{{ .Values.resources.requests.memory }}"
