apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}
    {{- if .Values.global.clientConfig.bcGov.enabled }}
    DataClass: {{ .Values.global.clientConfig.bcGov.dataClass | quote }}
    {{- end }}
  name: {{ .Chart.Name }}
spec:
  ports:
  - name: {{ .Chart.Name }}
    port: {{.Values.ingress.port}}
    targetPort: {{.Values.ingress.port}}
  selector:
    app: {{ .Chart.Name }}
